
== Create a complete AWS cluster with Terraform

TODO describe cluster resources (VPC, subnets, gatweays, etc)


=== Terraform commands

Download form here: [https://www.terraform.io/downloads.html]

Before executing any of the Terraform commands the environment variables `AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY`
needs to be set with the appropriate AWS credentials.

terraform init ::
    The terraform init command is used to initialize a working directory containing Terraform configuration files.

terraform get ::
    The terraform get command is used to download and update modules mentioned in the root module.

terraform plan -input=false ::
    This command is a convenient way to check whether the execution plan for a set of changes matches your expectations
    without making any changes to real resources or to the state

terraform apply -input=false ::
    The terraform apply command is used to apply the changes required to reach the desired state of the configuration, or
    the pre-determined set of actions generated by a terraform plan execution plan.

terraform destroy ::
    The terraform destroy command is used to destroy the Terraform-managed infrastructure.

